//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: cosmos/nft/tx.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Msg defines the nft Msg service.
///
/// Usage: instantiate `Imversed_Nft_MsgClient`, then call methods of this protocol to make API calls.
internal protocol Imversed_Nft_MsgClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Imversed_Nft_MsgClientInterceptorFactoryProtocol? { get }

  func issueDenom(
    _ request: Imversed_Nft_MsgIssueDenom,
    callOptions: CallOptions?
  ) -> UnaryCall<Imversed_Nft_MsgIssueDenom, Imversed_Nft_MsgIssueDenomResponse>

  func mintNFT(
    _ request: Imversed_Nft_MsgMintNFT,
    callOptions: CallOptions?
  ) -> UnaryCall<Imversed_Nft_MsgMintNFT, Imversed_Nft_MsgMintNFTResponse>

  func editNFT(
    _ request: Imversed_Nft_MsgEditNFT,
    callOptions: CallOptions?
  ) -> UnaryCall<Imversed_Nft_MsgEditNFT, Imversed_Nft_MsgEditNFTResponse>

  func transferNFT(
    _ request: Imversed_Nft_MsgTransferNFT,
    callOptions: CallOptions?
  ) -> UnaryCall<Imversed_Nft_MsgTransferNFT, Imversed_Nft_MsgTransferNFTResponse>

  func burnNFT(
    _ request: Imversed_Nft_MsgBurnNFT,
    callOptions: CallOptions?
  ) -> UnaryCall<Imversed_Nft_MsgBurnNFT, Imversed_Nft_MsgBurnNFTResponse>

  func transferDenom(
    _ request: Imversed_Nft_MsgTransferDenom,
    callOptions: CallOptions?
  ) -> UnaryCall<Imversed_Nft_MsgTransferDenom, Imversed_Nft_MsgTransferDenomResponse>
}

extension Imversed_Nft_MsgClientProtocol {
  internal var serviceName: String {
    return "imversed.nft.Msg"
  }

  /// IssueDenom defines a method for issue a denom.
  ///
  /// - Parameters:
  ///   - request: Request to send to IssueDenom.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func issueDenom(
    _ request: Imversed_Nft_MsgIssueDenom,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Imversed_Nft_MsgIssueDenom, Imversed_Nft_MsgIssueDenomResponse> {
    return self.makeUnaryCall(
      path: "/imversed.nft.Msg/IssueDenom",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeIssueDenomInterceptors() ?? []
    )
  }

  /// MintNFT defines a method for mint a new nft
  ///
  /// - Parameters:
  ///   - request: Request to send to MintNFT.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func mintNFT(
    _ request: Imversed_Nft_MsgMintNFT,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Imversed_Nft_MsgMintNFT, Imversed_Nft_MsgMintNFTResponse> {
    return self.makeUnaryCall(
      path: "/imversed.nft.Msg/MintNFT",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMintNFTInterceptors() ?? []
    )
  }

  /// RefundHTLC defines a method for editing a nft.
  ///
  /// - Parameters:
  ///   - request: Request to send to EditNFT.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func editNFT(
    _ request: Imversed_Nft_MsgEditNFT,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Imversed_Nft_MsgEditNFT, Imversed_Nft_MsgEditNFTResponse> {
    return self.makeUnaryCall(
      path: "/imversed.nft.Msg/EditNFT",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEditNFTInterceptors() ?? []
    )
  }

  /// TransferNFT defines a method for transferring a nft.
  ///
  /// - Parameters:
  ///   - request: Request to send to TransferNFT.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func transferNFT(
    _ request: Imversed_Nft_MsgTransferNFT,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Imversed_Nft_MsgTransferNFT, Imversed_Nft_MsgTransferNFTResponse> {
    return self.makeUnaryCall(
      path: "/imversed.nft.Msg/TransferNFT",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTransferNFTInterceptors() ?? []
    )
  }

  /// BurnNFT defines a method for burning a nft.
  ///
  /// - Parameters:
  ///   - request: Request to send to BurnNFT.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func burnNFT(
    _ request: Imversed_Nft_MsgBurnNFT,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Imversed_Nft_MsgBurnNFT, Imversed_Nft_MsgBurnNFTResponse> {
    return self.makeUnaryCall(
      path: "/imversed.nft.Msg/BurnNFT",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBurnNFTInterceptors() ?? []
    )
  }

  /// TransferDenom defines a method for transferring a denom.
  ///
  /// - Parameters:
  ///   - request: Request to send to TransferDenom.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func transferDenom(
    _ request: Imversed_Nft_MsgTransferDenom,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Imversed_Nft_MsgTransferDenom, Imversed_Nft_MsgTransferDenomResponse> {
    return self.makeUnaryCall(
      path: "/imversed.nft.Msg/TransferDenom",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTransferDenomInterceptors() ?? []
    )
  }
}

internal protocol Imversed_Nft_MsgClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'issueDenom'.
  func makeIssueDenomInterceptors() -> [ClientInterceptor<Imversed_Nft_MsgIssueDenom, Imversed_Nft_MsgIssueDenomResponse>]

  /// - Returns: Interceptors to use when invoking 'mintNFT'.
  func makeMintNFTInterceptors() -> [ClientInterceptor<Imversed_Nft_MsgMintNFT, Imversed_Nft_MsgMintNFTResponse>]

  /// - Returns: Interceptors to use when invoking 'editNFT'.
  func makeEditNFTInterceptors() -> [ClientInterceptor<Imversed_Nft_MsgEditNFT, Imversed_Nft_MsgEditNFTResponse>]

  /// - Returns: Interceptors to use when invoking 'transferNFT'.
  func makeTransferNFTInterceptors() -> [ClientInterceptor<Imversed_Nft_MsgTransferNFT, Imversed_Nft_MsgTransferNFTResponse>]

  /// - Returns: Interceptors to use when invoking 'burnNFT'.
  func makeBurnNFTInterceptors() -> [ClientInterceptor<Imversed_Nft_MsgBurnNFT, Imversed_Nft_MsgBurnNFTResponse>]

  /// - Returns: Interceptors to use when invoking 'transferDenom'.
  func makeTransferDenomInterceptors() -> [ClientInterceptor<Imversed_Nft_MsgTransferDenom, Imversed_Nft_MsgTransferDenomResponse>]
}

internal final class Imversed_Nft_MsgClient: Imversed_Nft_MsgClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Imversed_Nft_MsgClientInterceptorFactoryProtocol?

  /// Creates a client for the imversed.nft.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Imversed_Nft_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Msg defines the nft Msg service.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Imversed_Nft_MsgProvider: CallHandlerProvider {
  var interceptors: Imversed_Nft_MsgServerInterceptorFactoryProtocol? { get }

  /// IssueDenom defines a method for issue a denom.
  func issueDenom(request: Imversed_Nft_MsgIssueDenom, context: StatusOnlyCallContext) -> EventLoopFuture<Imversed_Nft_MsgIssueDenomResponse>

  /// MintNFT defines a method for mint a new nft
  func mintNFT(request: Imversed_Nft_MsgMintNFT, context: StatusOnlyCallContext) -> EventLoopFuture<Imversed_Nft_MsgMintNFTResponse>

  /// RefundHTLC defines a method for editing a nft.
  func editNFT(request: Imversed_Nft_MsgEditNFT, context: StatusOnlyCallContext) -> EventLoopFuture<Imversed_Nft_MsgEditNFTResponse>

  /// TransferNFT defines a method for transferring a nft.
  func transferNFT(request: Imversed_Nft_MsgTransferNFT, context: StatusOnlyCallContext) -> EventLoopFuture<Imversed_Nft_MsgTransferNFTResponse>

  /// BurnNFT defines a method for burning a nft.
  func burnNFT(request: Imversed_Nft_MsgBurnNFT, context: StatusOnlyCallContext) -> EventLoopFuture<Imversed_Nft_MsgBurnNFTResponse>

  /// TransferDenom defines a method for transferring a denom.
  func transferDenom(request: Imversed_Nft_MsgTransferDenom, context: StatusOnlyCallContext) -> EventLoopFuture<Imversed_Nft_MsgTransferDenomResponse>
}

extension Imversed_Nft_MsgProvider {
  internal var serviceName: Substring { return "imversed.nft.Msg" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "IssueDenom":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Imversed_Nft_MsgIssueDenom>(),
        responseSerializer: ProtobufSerializer<Imversed_Nft_MsgIssueDenomResponse>(),
        interceptors: self.interceptors?.makeIssueDenomInterceptors() ?? [],
        userFunction: self.issueDenom(request:context:)
      )

    case "MintNFT":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Imversed_Nft_MsgMintNFT>(),
        responseSerializer: ProtobufSerializer<Imversed_Nft_MsgMintNFTResponse>(),
        interceptors: self.interceptors?.makeMintNFTInterceptors() ?? [],
        userFunction: self.mintNFT(request:context:)
      )

    case "EditNFT":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Imversed_Nft_MsgEditNFT>(),
        responseSerializer: ProtobufSerializer<Imversed_Nft_MsgEditNFTResponse>(),
        interceptors: self.interceptors?.makeEditNFTInterceptors() ?? [],
        userFunction: self.editNFT(request:context:)
      )

    case "TransferNFT":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Imversed_Nft_MsgTransferNFT>(),
        responseSerializer: ProtobufSerializer<Imversed_Nft_MsgTransferNFTResponse>(),
        interceptors: self.interceptors?.makeTransferNFTInterceptors() ?? [],
        userFunction: self.transferNFT(request:context:)
      )

    case "BurnNFT":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Imversed_Nft_MsgBurnNFT>(),
        responseSerializer: ProtobufSerializer<Imversed_Nft_MsgBurnNFTResponse>(),
        interceptors: self.interceptors?.makeBurnNFTInterceptors() ?? [],
        userFunction: self.burnNFT(request:context:)
      )

    case "TransferDenom":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Imversed_Nft_MsgTransferDenom>(),
        responseSerializer: ProtobufSerializer<Imversed_Nft_MsgTransferDenomResponse>(),
        interceptors: self.interceptors?.makeTransferDenomInterceptors() ?? [],
        userFunction: self.transferDenom(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Imversed_Nft_MsgServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'issueDenom'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeIssueDenomInterceptors() -> [ServerInterceptor<Imversed_Nft_MsgIssueDenom, Imversed_Nft_MsgIssueDenomResponse>]

  /// - Returns: Interceptors to use when handling 'mintNFT'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMintNFTInterceptors() -> [ServerInterceptor<Imversed_Nft_MsgMintNFT, Imversed_Nft_MsgMintNFTResponse>]

  /// - Returns: Interceptors to use when handling 'editNFT'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeEditNFTInterceptors() -> [ServerInterceptor<Imversed_Nft_MsgEditNFT, Imversed_Nft_MsgEditNFTResponse>]

  /// - Returns: Interceptors to use when handling 'transferNFT'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeTransferNFTInterceptors() -> [ServerInterceptor<Imversed_Nft_MsgTransferNFT, Imversed_Nft_MsgTransferNFTResponse>]

  /// - Returns: Interceptors to use when handling 'burnNFT'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeBurnNFTInterceptors() -> [ServerInterceptor<Imversed_Nft_MsgBurnNFT, Imversed_Nft_MsgBurnNFTResponse>]

  /// - Returns: Interceptors to use when handling 'transferDenom'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeTransferDenomInterceptors() -> [ServerInterceptor<Imversed_Nft_MsgTransferDenom, Imversed_Nft_MsgTransferDenomResponse>]
}
